 
a) Types of information used by various functions;
b) Frequency of use;
c) Accessing capabilities;
d) Data entities and their relationships;
e) Integrity constraints;
f) Data retention requirements.


Coordinates should conform to the World Geodetic System 84.

* Waypoint

The waypoint data facilitates the function of providing map coordinates entered by the user to be displayed on the device and as a reference towards the track data.
The data have to conform to the open xml format of GPS eXchange Format(could use GML instead) as it is higly compatible and translateble towards other mapping formats and applications.
The waypoint data must contain the following attributes:
Name of route.
Name for each waypoint
Valid Coordinates in longitude and latitude.
Elevation. 
The user must be able to view and modify the data in varius abstractions either through the device itself or by using the device as a usb slave peripheral.
The waypoint data will in most cases only be read by the system as it is a reference only and will seldom be updated by the user.


** DATA INTEGRITY AND RETENTION

The waypoint data can not by any means be modyfied by the system unless it is requested by the user.
The waypoint data should be persistently stored on a non-volatile storage medium to prevent data loss.
The waypoint data can be bufferd onto volatile storage medium if performance is needed.
The waypoint data should be verified to be correct before and after transfering it between storage mediums.
If clobbering would occur between two different data files, user verification is needed to proceed.

Data Format: GPS eXchange Format
GPS eXchange Format(gpx) is a de facto standard for storing gps data.[ref]
Accessing capabilities:
User:
The database of waypoints must be stored in a visible partition allowing access for the user through the capabilities of slave usb mode,
 the entity should be read and writable.
System:
The system access the same entity as the 







* User Location or Track

The track data facilitates the function of providing and storing information about the device location history.
It will be used to show the device current and past locations on the device display.
The user can mark single entries as significant waypoints and therefore assign a name of that entry.

** FORMATTING

The track data entries have to contain the following attributes:

Valid Coordinates in longitude and latitude.
Elevation in meters rounded to one decimal place.
Time when location was accuried.
Heading rounded to one decimal place.
Optional:
Name of entry.

The trackdata should conform to an ordered list where first entry is the oldest entry relative to time.

** Use
The trackdata will be continusly appended by the system when the gps is active and read to update the display.


** DATA INTEGRITY AND RETENTION
The only operation allowed by the system alone is permission to append new track data.
The system can not modify nor remove any exsisting trackdata, unless promted by the user. // fix scentence 
The track data is not allowed to soly excist on volatile storage medium.
Track data is required to be persistently stored on a non-volatile storage medium to prevent data loss.
Track data can be bufferd onto volatile storage medium if performance is needed.
Track data is not allowed to be clobbered.
Track data stored on non-volatile medium have highest priority to be updated when new gps data is acquired.
Track data should be verified to be correct before and after transfering it between storage mediums.




Data Format: GPS eXchange Format



Data retention:  Major requirement, 


* System variables




* ref;
http://en.wikipedia.org/wiki/World_Geodetic_System https://www1.nga.mil/ProductsServices/GeodesyandGeophysics/WorldGeodeticSystem/Pages/default.aspx
http://en.wikipedia.org/wiki/GPS_eXchange_Format
Using and Abusing XML http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=04455638
