 
a) Types of information used by various functions;
b) Frequency of use;
c) Accessing capabilities;
d) Data entities and their relationships;
e) Integrity constraints;
f) Data retention requirements.


Coordinates should conform to the World Geodetic System 84.

* Waypoint

The waypoint data facilitates the function of providing map coordinates entered by the user to be displayed on the device and as a reference towards the track data.
The data have to conform to the open xml format of GPS eXchange Format(could use GML instead) as it is higly compatible and translateble towards other mapping formats and applications.
The waypoint data must contain the following attributes:
Name of route.
Name for each waypoint
Valid Coordinates in longitude and latitude.
Elevation. 
The user must be able to view and modify the data in varius abstractions either through the device itself or by using the device as a usb slave peripheral.
The waypoint data will in most cases only be read by the system as it is a reference only and will seldom be updated by the user.


** DATA INTEGRITY AND RETENTION

The waypoint data can not by any means be modyfied by the system unless it is requested by the user.
The waypoint data should be persistently stored on a non-volatile storage medium to prevent data loss.
The waypoint data can be bufferd onto volatile storage medium if performance is needed.
The waypoint data should be verified to be correct before and after transfering it between storage mediums.
If clobbering would occur between two different data files, user verification is needed to proceed.

Data Format: GPS eXchange Format
GPS eXchange Format(gpx) is a de facto standard for storing gps data.[ref]
Accessing capabilities:
User:
The database of waypoints must be stored in a visible partition allowing access for the user through the capabilities of slave usb mode,
 the entity should be read and writable.
System:
The system access the same entity as the 







* User Location or Track

The track data facilitates the function of providing and storing information about the device location history.
It will be used to show the device current and past locations on the device display.
The user can mark single entries as significant waypoints and therefore assign a name of that entry.

** FORMATTING

The track data entries have to contain the following attributes:

Valid Coordinates in longitude and latitude.
Elevation in meters rounded to one decimal place.
Time when location was accuried.
Heading rounded to one decimal place.
Optional:
Name of entry.

The trackdata should conform to an ordered list where first entry is the oldest entry relative to time.

** Use
*** System 
The trackdata will be continusly appended by the system when the gps is active and read to update the display.
The system will access the the track data to display it on the device.
*** User
The user can mark entries to waypoints.
The user can delete track data.
The user can transfer track data though usb.

** DATA INTEGRITY AND RETENTION
The only operation allowed by the system alone is permission to append new track data.
The system can not modify nor remove any exsisting trackdata, unless promted by the user. // fix scentence 
The track data is not allowed to soly excist on volatile storage medium.
Track data is required to be persistently stored on a non-volatile storage medium to prevent data loss.
Track data can be bufferd onto volatile storage medium if performance is needed.
Track data is not allowed to be clobbered.
Track data stored on non-volatile medium have highest priority to be updated when new gps data is acquired.
Track data should be verified to be correct before and after transfering it between storage mediums.




Data Format: GPS eXchange Format



Data retention:  Major requirement, 


* System variables





Consice




Types of data
The device has two main databases that contain of waypoint data and track data. This data should be of the open xml format GPS eXchange Format to enable easy conversion and use in geographical applications. The waypoint data is pre generated entries consisting of geographical coordinates in longitude and latitude, the name of the route, name of individual entries and elevation information at that location. 
The waypoint data is created by the user either on the device or transferred from a computer. The track data is generated from data acquired from the GPS device. Each track entry consists of geographical coordinates in longitude and latitude, elevation, entry time, heading and the extension name.
Data integrity and retention
To ensure the security and satisfaction of the device, precautions have to be taken on how to input and store the data. To prevent data loss or corruption, all waypoint and track data have to be stored on a non-volatile storage medium and during transfer between mediums the data have to be verified before and after the transfer. The data is allowed to reside in volatile memory as long as a master copy is stored on non-volatile storage. The device should not be able to modify nor delete any data without user prompt, however appending to the data files is allowed without user input. Track data is never allowed to be clobbered and waypoint data needs verification from the user before clobbering.
Data access input output
User
The user should be able to access the data in two ways, by using the device or by using a computer. 
The waypoint and track data will be accessed to display information about the locations of waypoints and the device in relation to each other. It will also be used to calculate and output data such as distance travelled, average speed and distance to destination to the user. The user can also mark certain track entries as special points of interest.
The data should be stored at such logical location so that when the user connects the device to a computer, the user can access the data and upload new data if chosen to.
System
The system will periodically receive geographical data from the GPS that needs to be processed and appended to the track data. 


* ref;
http://en.wikipedia.org/wiki/World_Geodetic_System https://www1.nga.mil/ProductsServices/GeodesyandGeophysics/WorldGeodeticSystem/Pages/default.aspx
http://en.wikipedia.org/wiki/GPS_eXchange_Format
Using and Abusing XML http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=04455638

